### PR TITLE
PPP + UG (Add find, improve list and edit)

### PR DESCRIPTION
**Pull request by TPH777**

### CODE REVIEW

**Comment by TPH777** [comment]
On a side note, I was wondering is there really a need to separate incomes and spendings instructions.

**Comment by NigelYeoTW** [comment]
lgtm

**Comment by NigelYeoTW** [comment]
> On a side note, I was wondering is there really a need to separate incomes and spendings instructions.

I think can just leave it so less confusing I think user guide need explore all the possibilities

**Comment by NigelYeoTW** [comment]
> > On a side note, I was wondering is there really a need to separate incomes and spendings instructions.
> 
> I think can just leave it so less confusing I think user guide need explore all the possibilities

But in command summary actually can combine for certain commands i guess since they are identical, for list cause spending still got statistics so should separate

**Comment by NigelYeoTW** [comment]
alright lgtm

**Pull request merged**
