### PR TITLE
solving bugs related to doubles

### PR DESCRIPTION
**Pull request by wongwh2002**

### CODE REVIEW

**Comment by wongwh2002** [comment]
have to add test for double for all of the test cases

**Comment by wongwh2002** [comment]
also is there a way to write test case such that if 1 thing change we dont to change everything else

**Comment by wongwh2002** [comment]
also now the spendinglist and incomelist got repeated @overwrite, should we refractor out

**Comment by NigelYeoTW** [comment]
lgtm

**Pull request merged**
